[workspace]
members = [
    "zkevm-circuits",
    "bus-mapping",
    "geth-utils",
    "keccak256",
    "zktrie",
    "gadgets",
    "integration-tests",
    "circuit-benchmarks",
    "eth-types",
    "external-tracer",
    "mock",
    "testool",
    "aggregator",
    "prover"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0"
ark-std = "0.3"
base64 = "0.13.0"
ctor = "0.1"
env_logger = "0.10"
ethers = { version = "=2.0.7", features = ["ethers-solc"] }
ethers-core = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.10.0rc3", features = ["scroll"] }
ethers-providers = "=2.0.7"
ethers-signers = "=2.0.7"
ff = "0.13"
halo2_proofs = { git = "https://github.com/kroma-network/halo2.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
hash-circuit = { package = "poseidon-circuit", git = "https://github.com/kroma-network/poseidon-circuit.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
halo2-base = { git = "https://github.com/kroma-network/halo2-lib", branch = "feat/upstream-scroll-v0.10.0rc3", default-features=false, features=["halo2-pse","display"] }
halo2-ecc = { git = "https://github.com/kroma-network/halo2-lib", branch = "feat/upstream-scroll-v0.10.0rc3", default-features=false, features=["halo2-pse","display"] }
hex = "0.4"
itertools = "0.11"
lazy_static = "1.4"
libsecp256k1 = "0.7"
log = "0.4"
num = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
pretty_assertions = "1.0"
once_cell = "1.17"
rand = "0.8"
rand_chacha = "0.3"
rand_xorshift = "0.3"
rayon = "1.5"
regex = "1.5"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_stacker = "0.1"
sha3 = "0.10"
snark-verifier = { git = "https://github.com/kroma-network/snark-verifier", branch = "feat/upstream-scroll-v0.10.0rc3" }
snark-verifier-sdk = { git = "https://github.com/kroma-network/snark-verifier", branch = "feat/upstream-scroll-v0.10.0rc3", default-features = false, features = ["loader_halo2", "loader_evm", "halo2-pse"] }
strum = "0.25"
strum_macros = "0.25"
subtle = "2.4"
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
url = "2.2"
revm-precompile = { git = "https://github.com/kroma-network/revm.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
c-kzg = "1.0.0"

[patch.crates-io]
ethers-core = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
ethers-providers = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
ethers = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
ethers-etherscan = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
ethers-signers  = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
gobuild = { git = "https://github.com/scroll-tech/gobuild.git" }
halo2curves = { git = "https://github.com/kroma-network/halo2curves", branch = "feat/upstream-scroll-v0.10.0rc3" }

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git = "https://github.com/kroma-network/halo2.git", branch = "feat/upstream-scroll-v0.10.0rc3" }
[patch."https://github.com/privacy-scaling-explorations/poseidon.git"]
poseidon = { git = "https://github.com/kroma-network/poseidon.git", branch = "feat/upstream-scroll-v0.10.0rc3" }

[patch."https://github.com/privacy-scaling-explorations/bls12_381"]
bls12_381 = { git = "https://github.com/kroma-network/bls12_381", branch = "feat/upstream-scroll-v0.10.0rc3" }



# Definition of benchmarks profile to use.
[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
rpath = false
lto = "thin"
incremental = true

[profile.release]
opt-level = 3
debug = false
debug-assertions = true
overflow-checks = true
rpath = false
lto = "thin"
incremental = true
