[workspace]
members = [
    "zkevm-circuits",
    "bus-mapping",
    "geth-utils",
    "keccak256",
    "zktrie",
    "gadgets",
    "integration-tests",
    "circuit-benchmarks",
    "eth-types",
    "external-tracer",
    "mock",
    "testool",
    "aggregator",
    "prover"
]

[patch.crates-io]
ethers-core = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.9.9" }
ethers-signers = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.9.9" }
ethers-etherscan = { git = "https://github.com/kroma-network/ethers-rs.git", branch = "feat/upstream-scroll-v0.9.9" }
[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git = "https://github.com/kroma-network/halo2.git", branch = "feat/upstream-scroll-v0.9.9" }
[patch."https://github.com/privacy-scaling-explorations/poseidon.git"]
poseidon = { git = "https://github.com/kroma-network/poseidon.git", branch = "feat/upstream-scroll-v0.9.9" }
[patch."https://github.com/privacy-scaling-explorations/halo2curves.git"]
halo2curves = { git = "https://github.com/kroma-network/halo2curves.git", branch = "feat/upstream-scroll-v0.9.9" }
[patch."https://github.com/privacy-scaling-explorations/halo2wrong.git"]
maingate = { git = "https://github.com/kroma-network/halo2wrong", branch = "feat/upstream-scroll-v0.9.9" }

# Definition of benchmarks profile to use.
[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
rpath = false
lto = "thin"
incremental = true

[profile.release]
opt-level = 3
debug = false
debug-assertions = true
overflow-checks = true
rpath = false
lto = "thin"
incremental = true
