//! Mock types and functions to generate Test enviroments for ZKEVM tests

use crate::{eth, MockAccount, MockBlock, MockTransaction};
#[cfg(feature = "kanvas")]
use eth_types::{
    geth_types::DEPOSIT_TX_TYPE,
    kanvas_l1_block::BYTECODE,
    kanvas_params::{BASE_FEE_RECIPIENT, L1_BLOCK, L1_FEE_RECIPIENT, SYSTEM_TX_CALLER},
    Bytes,
};
use eth_types::{
    geth_types::{Account, BlockConstants, GethData},
    Block, Bytecode, Error, GethExecTrace, Transaction, Word,
};
use external_tracer::{trace, TraceConfig};
use helpers::*;
use itertools::Itertools;

pub use external_tracer::LoggerConfig;

/// TestContext is a type that contains all the information from a block
/// required to build the circuit inputs.
///
/// It is specifically used to generate Test cases with very precise information
/// details about any specific part of a block. That includes of course, its
/// transactions too and the accounts involved in all of them.
///
/// The intended way to interact with the structure is through the fn `new`
/// which is designed to return a [`GethData`] which then can be used to query
/// any specific part of the logs generated by the transactions executed within
/// this context.
///
/// ## Example
/// ```rust
/// use eth_types::evm_types::{stack::Stack, Gas, OpcodeId};
/// use eth_types::{address, bytecode, geth_types::GethData, word, Bytecode, ToWord, Word};
/// use lazy_static::lazy_static;
/// use mock::test_ctx::{helpers::*, TestContext};
/// // code_a calls code
/// // jump to 0x10 which is outside the code (and also not marked with
///         // JUMPDEST)
/// let code = bytecode! {
///     PUSH1(0x10)
///     JUMP
///     STOP
/// };
/// let code_a = bytecode! {
///     PUSH1(0x0) // retLength
///     PUSH1(0x0) // retOffset
///     PUSH1(0x0) // argsLength
///     PUSH1(0x0) // argsOffset
///     PUSH32(address!("0x000000000000000000000000000000000cafe001").to_word()) // addr
///     PUSH32(0x1_0000) // gas
///     STATICCALL
///     PUSH2(0xaa)
/// };
/// let index = 8; // JUMP
///
/// // Get the execution steps from the external tracer
/// let block: GethData = TestContext::<3, 2>::new(
///     None,
///     |accs| {
///         accs[0]
///             .address(address!("0x0000000000000000000000000000000000000000"))
///             .code(code_a);
///         accs[1].address(address!("0x000000000000000000000000000000000cafe001")).code(code);
///         accs[2]
///             .address(address!("0x000000000000000000000000000000000cafe002"))
///             .balance(Word::from(1u64 << 30));
///     },
///     |mut txs, accs| {
///         txs[0].to(accs[0].address).from(accs[2].address);
///         txs[1]
///             .to(accs[1].address)
///             .from(accs[2].address)
///             .nonce(Word::one());
///     },
///     |block, _tx| block.number(0xcafeu64),
/// )
/// .unwrap()
/// .into();
///
/// // Now we can start generating the traces and items we need to inspect
/// // the behaviour of the generated env.
/// ```
#[derive(Debug)]
pub struct TestContext<const NACC: usize, const NTX: usize> {
    /// chain id
    pub chain_id: Word,
    /// Account list
    pub accounts: [Account; NACC],
    /// history hashes contains most recent 256 block hashes in history, where
    /// the lastest one is at history_hashes[history_hashes.len() - 1].
    pub history_hashes: Vec<Word>,
    /// Block from geth
    pub eth_block: eth_types::Block<eth_types::Transaction>,
    /// Execution Trace from geth
    pub geth_traces: [eth_types::GethExecTrace; NTX],
}

#[cfg(feature = "kanvas")]
#[macro_export]
macro_rules! tx_idx {
    ($n: expr) => {
        $n + 1
    };
}
#[cfg(not(feature = "kanvas"))]
#[macro_export]
macro_rules! tx_idx {
    ($n: expr) => {
        $n
    };
}

#[cfg(feature = "kanvas")]
macro_rules! nonce {
    ($n: expr) => {
        $n - 1
    };
}
#[cfg(not(feature = "kanvas"))]
macro_rules! nonce {
    ($n: expr) => {
        $n
    };
}

#[cfg(feature = "kanvas")]
#[macro_export]
// Following accounts are added.
// - $NACC - 4: L1Block.sol
// - $NACC - 3: SystemTxDepositor
// - $NACC - 2: BaseFeeRecipient
// - $NACC - 1: L1FeeRecipient
// Following txs are added at the beginning.
// - 0: SystemDepositTx.
macro_rules! declare_test_context {
    ($ty: ident, $NACC: expr, $NTX: expr) => {
        type $ty = TestContext<{ $NACC + 4 }, { $NTX + 1 }>;
    };
}
#[cfg(not(feature = "kanvas"))]
#[macro_export]
macro_rules! declare_test_context {
    ($ty: ident, $NACC: expr, $NTX: expr) => {
        type $ty = TestContext<$NACC, $NTX>;
    };
}

declare_test_context!(TestContext2_1_, 2, 1);
pub type TestContext2_1 = TestContext2_1_;

declare_test_context!(TestContext3_1_, 3, 1);
pub type TestContext3_1 = TestContext3_1_;

declare_test_context!(TestContext3_2_, 3, 2);
pub type TestContext3_2 = TestContext3_2_;

pub type SimpleTestContext = TestContext2_1;

impl<const NACC: usize, const NTX: usize> From<TestContext<NACC, NTX>> for GethData {
    fn from(ctx: TestContext<NACC, NTX>) -> GethData {
        GethData {
            chain_id: ctx.chain_id,
            history_hashes: ctx.history_hashes,
            eth_block: ctx.eth_block,
            geth_traces: ctx.geth_traces.to_vec(),
            accounts: ctx.accounts.into(),
        }
    }
}

impl<const NACC: usize, const NTX: usize> TestContext<NACC, NTX> {
    pub fn new_with_logger_config<FAcc, FTx, Fb>(
        history_hashes: Option<Vec<Word>>,
        acc_fns: FAcc,
        func_tx: FTx,
        func_block: Fb,
        logger_config: LoggerConfig,
    ) -> Result<Self, Error>
    where
        FTx: FnOnce(Vec<&mut MockTransaction>, [MockAccount; NACC]),
        Fb: FnOnce(&mut MockBlock, Vec<MockTransaction>) -> &mut MockBlock,
        FAcc: FnOnce([&mut MockAccount; NACC]),
    {
        let mut accounts: Vec<MockAccount> = vec![MockAccount::default(); NACC];
        // Build Accounts modifiers
        let account_refs = accounts
            .iter_mut()
            .collect_vec()
            .try_into()
            .expect("Mismatched len err");
        acc_fns(account_refs);
        let accounts: [MockAccount; NACC] = accounts
            .iter_mut()
            .map(|acc| acc.build())
            .collect_vec()
            .try_into()
            .expect("Mismatched acc len");

        let mut transactions = vec![MockTransaction::default(); NTX];
        // By default, set the TxIndex and the Nonce values of the multiple transactions
        // of the context correlative so that any Ok test passes by default.
        // If the user decides to override these values, they'll then be set to whatever
        // inputs were provided by the user.
        transactions
            .iter_mut()
            .enumerate()
            .skip(1)
            .for_each(|(idx, tx)| {
                tx.transaction_idx(u64::try_from(idx).expect("Unexpected idx conversion error"));
                tx.nonce(Word::from(
                    u64::try_from(nonce!(idx)).expect("Unexpected idx conversion error"),
                ));
            });
        let tx_refs = transactions.iter_mut().collect();

        // Build Tx modifiers.
        func_tx(tx_refs, accounts.clone());
        let transactions: Vec<MockTransaction> =
            transactions.iter_mut().map(|tx| tx.build()).collect();

        // Build Block modifiers
        let mut block = MockBlock::default();
        block.transactions.extend_from_slice(&transactions);
        func_block(&mut block, transactions).build();

        let chain_id = block.chain_id;
        let block = Block::<Transaction>::from(block);
        let accounts: [Account; NACC] = accounts
            .iter()
            .cloned()
            .map(Account::from)
            .collect_vec()
            .try_into()
            .expect("Mismatched acc len");

        let geth_traces = gen_geth_traces(
            chain_id,
            block.clone(),
            accounts.clone(),
            history_hashes.clone(),
            logger_config,
        )?;

        Ok(Self {
            chain_id,
            accounts,
            history_hashes: history_hashes.unwrap_or_default(),
            eth_block: block,
            geth_traces,
        })
    }

    /// Create a new TestContext which starts with `NACC` default accounts and
    /// `NTX` default transactions.  Afterwards, we apply the `acc_fns`
    /// function to the accounts, the `func_tx` to the transactions and
    /// the `func_block` to the block, where each of these functions can
    /// mutate their target using the builder pattern. Finally an
    /// execution trace is generated of the resulting input block and state.
    pub fn new<FAcc, FTx, Fb>(
        history_hashes: Option<Vec<Word>>,
        acc_fns: FAcc,
        func_tx: FTx,
        func_block: Fb,
    ) -> Result<Self, Error>
    where
        FTx: FnOnce(Vec<&mut MockTransaction>, [MockAccount; NACC]),
        Fb: FnOnce(&mut MockBlock, Vec<MockTransaction>) -> &mut MockBlock,
        FAcc: FnOnce([&mut MockAccount; NACC]),
    {
        Self::new_with_logger_config(
            history_hashes,
            acc_fns,
            func_tx,
            func_block,
            LoggerConfig::default(),
        )
    }

    /// Returns a simple TestContext setup with a single tx executing the
    /// bytecode passed as parameters. The balances of the 2 accounts and
    /// addresses are the ones used in [`TestContext::
    /// account_0_code_account_1_no_code`]. Extra accounts, txs and/or block
    /// configs are set as [`Default`].
    pub fn simple_ctx_with_bytecode(bytecode: Bytecode) -> Result<SimpleTestContext, Error> {
        TestContext::new(
            None,
            account_0_code_account_1_no_code(bytecode),
            tx_from_1_to_0,
            |block, _txs| block.number(0xcafeu64),
        )
    }
}

/// Generates execution traces for the transactions included in the provided
/// Block
fn gen_geth_traces<const NACC: usize, const NTX: usize>(
    chain_id: Word,
    block: Block<Transaction>,
    accounts: [Account; NACC],
    history_hashes: Option<Vec<Word>>,
    logger_config: LoggerConfig,
) -> Result<[GethExecTrace; NTX], Error> {
    let trace_config = TraceConfig {
        chain_id,
        history_hashes: history_hashes.unwrap_or_default(),
        block_constants: BlockConstants::try_from(&block)?,
        accounts: accounts
            .iter()
            .map(|account| (account.address, account.clone()))
            .collect(),
        transactions: block
            .transactions
            .iter()
            .map(eth_types::geth_types::Transaction::from)
            .collect(),
        logger_config,
    };
    let traces = trace(&trace_config)?;
    let result: [GethExecTrace; NTX] = traces.try_into().expect("Unexpected len mismatch");
    Ok(result)
}

/// Collection of helper functions which contribute to specific rutines on the
/// builder pattern used to construct [`TestContext`]s.
pub mod helpers {
    use super::*;
    use crate::MOCK_ACCOUNTS;

    /// Generate a simple setup which adds balance to two default accounts from
    /// [`static@MOCK_ACCOUNTS`]:
    /// - 0x000000000000000000000000000000000cafe111
    /// - 0x000000000000000000000000000000000cafe222
    /// And injects the provided bytecode into the first one.
    fn do_account_0_code_account_1_no_code(accs: &mut [&mut MockAccount], code: Bytecode) {
        accs[0]
            .address(MOCK_ACCOUNTS[0])
            .balance(eth(10))
            .code(code);
        accs[1].address(MOCK_ACCOUNTS[1]).balance(eth(10));
    }

    #[cfg(feature = "kanvas")]
    /// Generate existing accounts in Kanvas.
    /// - L1_BLOCK
    /// - SYSTEM_TX_CALLER
    /// - BASE_FEE_RECIPIENT
    /// - L1_FEE_RECIPIENT
    pub fn setup_kanvas_required_accounts(accs: &mut [&mut MockAccount], n: usize) {
        accs[n].address(*L1_BLOCK).code(BYTECODE.clone());
        accs[n + 1].address(*SYSTEM_TX_CALLER);
        accs[n + 2].address(*BASE_FEE_RECIPIENT);
        accs[n + 3].address(*L1_FEE_RECIPIENT);
    }

    #[cfg(feature = "kanvas")]
    /// Intercept account_0_code_account_1_no_code and setup accounts for Kanvas
    /// unittest.
    pub fn account_0_code_account_1_no_code(code: Bytecode) -> impl FnOnce([&mut MockAccount; 6]) {
        |mut accs| {
            do_account_0_code_account_1_no_code(accs.as_mut_slice(), code);
            setup_kanvas_required_accounts(accs.as_mut_slice(), 2);
        }
    }

    #[cfg(not(feature = "kanvas"))]
    /// Do the exactly same with PSE existing account_0_code_account_1_no_code.
    pub fn account_0_code_account_1_no_code(code: Bytecode) -> impl FnOnce([&mut MockAccount; 2]) {
        |mut accs| {
            do_account_0_code_account_1_no_code(accs.as_mut_slice(), code);
        }
    }

    /// Generate a single transaction from the second account of the list to the
    /// first one.
    fn do_tx_from_1_to_0(tx: &mut MockTransaction, accs: &[MockAccount]) {
        tx.from(accs[1].address).to(accs[0].address);
    }

    #[cfg(feature = "kanvas")]
    /// Generate a system deposit transaction.
    pub fn system_deposit_tx(tx: &mut MockTransaction) {
        macro_rules! padding {
            ($vec:expr) => {{
                let mut v = $vec;
                let len = v.len();
                for _ in 0..(32 - len) {
                    v.insert(0, 0);
                }
                v
            }};
        }

        let mut calldata = Vec::with_capacity(4 + 32 * 8);
        calldata.extend(vec![0x01, 0x5d, 0x8e, 0xb9]); // setL1BlockValues
        calldata.extend(vec![0; 32]); // l1 blocknumber
        calldata.extend(vec![0; 32]); // l1 timestamp
        calldata.extend(padding!(vec![0x08])); // l1 basefee
        calldata.extend(vec![0; 32]); // l1 hash
        calldata.extend(vec![0; 32]); // sequenceNumber
        calldata.extend(vec![0; 32]); // batcherHash
        calldata.extend(padding!(vec![0x08, 0x34])); // l1 fee overhead
        calldata.extend(padding!(vec![0x0f, 0x42, 0x40])); // l1 fee scalar

        tx.transaction_type(DEPOSIT_TX_TYPE)
            .from(*SYSTEM_TX_CALLER)
            .to(*L1_BLOCK)
            .gas(Word::from(150000000))
            .gas_price(Word::zero())
            .input(Bytes::from(calldata));
    }

    #[cfg(feature = "kanvas")]
    /// Intercept tx_from_1_to_0 and add a system deposit transaction at the
    /// front.
    pub fn tx_from_1_to_0(mut txs: Vec<&mut MockTransaction>, accs: [MockAccount; 6]) {
        system_deposit_tx(txs[0]);
        do_tx_from_1_to_0(txs[1], accs.as_slice());
    }

    #[cfg(not(feature = "kanvas"))]
    pub fn tx_from_1_to_0(mut txs: Vec<&mut MockTransaction>, accs: [MockAccount; 2]) {
        do_tx_from_1_to_0(txs[0], accs.as_slice());
    }
}
