[package]
name = "bus-mapping"
version = "0.1.0"
edition = "2021"
authors = ["CPerezz <c.perezbaro@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
keccak256 = { path = "../keccak256" }
mock = { path = "../mock", optional = true }

ethers-core = "0.17.0"
ethers-signers = "0.17.0"
ethers-providers = "0.17.0"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_01_20" }
itertools = "0.10"
lazy_static = "1.4"
log = "0.4.14"
rand = { version = "0.8", optional = true }
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
strum = "0.24"
hex = "0.4.3"
strum_macros = "0.24"

# precompile related crates
fp-evm = { version = "3.0.0-dev", git = "https://github.com/paritytech/frontier", rev = "73e6223e8bc26bf8e57cd9b212f1bc2fd288c5ca" }
pallet-evm-precompile-blake2 = { version = "2.0.0-dev", git = "https://github.com/paritytech/frontier", rev = "73e6223e8bc26bf8e57cd9b212f1bc2fd288c5ca" }
pallet-evm-precompile-bn128 = { version = "2.0.0-dev", git = "https://github.com/paritytech/frontier", rev = "73e6223e8bc26bf8e57cd9b212f1bc2fd288c5ca" }
pallet-evm-precompile-curve25519 = { version = "1.0.0-dev", git = "https://github.com/paritytech/frontier", rev = "73e6223e8bc26bf8e57cd9b212f1bc2fd288c5ca" }
pallet-evm-precompile-modexp = { version = "2.0.0-dev", git = "https://github.com/paritytech/frontier", rev = "73e6223e8bc26bf8e57cd9b212f1bc2fd288c5ca" }
pallet-evm-precompile-simple = { version = "2.0.0-dev", git = "https://github.com/paritytech/frontier", rev = "73e6223e8bc26bf8e57cd9b212f1bc2fd288c5ca" }
primitive-types-12 = { package = "primitive-types", version = "0.12" }
once_cell = "1.17.0"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.0.0"
tokio = { version = "1.13", features = ["macros"] }
url = "2.2.2"
ctor = "0.1.22"
env_logger = "0.9.0"
mock = { path = "../mock" }
rand = "0.8"

[features]
default = []
kanvas = ["eth-types/kanvas"]
test = ["mock", "rand"]
