[package]
name = "mpt-zktrie"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }
mpt-circuits = { package = "halo2-mpt-circuits", git = "https://github.com/kroma-network/mpt-circuit.git", rev = "2a5e9e5" }
zktrie = { git = "https://github.com/kroma-network/zktrie.git", rev = "d33be94" }
bus-mapping = { path = "../bus-mapping" }
eth-types = { path = "../eth-types" }
lazy_static = "1.4"
num-bigint = { version = "0.4" }
log = "0.4"

[dev-dependencies]
env_logger = "0.9"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"

[features]
default = []
