[package]
name = "mpt-zktrie"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs.workspace = true
# mpt-circuits = { package = "halo2-mpt-circuits", git = "https://github.com/kroma-network/mpt-circuit.git", branch = "feat/upstream-scroll-v0.10.0rc3", default-features=false }
mpt-circuits = { path = "../../mpt-circuit", package = "halo2-mpt-circuits", default-features=false }
zktrie = { git = "https://github.com/kroma-network/zktrie.git", branch = "feat/upstream-scroll-v0.10.0rc3", default-features = false}
hash-circuit.workspace = true
eth-types = { path = "../eth-types" }
num-bigint.workspace = true
log.workspace = true
hex.workspace = true

[dev-dependencies]
env_logger.workspace = true
serde.workspace = true
serde_json.workspace = true

[features]
default = []
parallel_syn = ["mpt-circuits/parallel_syn"]

