[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/light-scale/halo2.git", branch = "ls-dev-0902" }
num = "0.4"
sha3 = "0.10"
array-init = "2.0.0"
bus-mapping = { path = "../bus-mapping" }
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
ethers-core = "0.17.0"
ethers-signers = "0.17.0"
mock = { path = "../mock" }
strum = "0.24"
strum_macros = "0.24"
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10.3"
lazy_static = "1.4"
keccak256 = { path = "../keccak256"}
log = "0.4"
env_logger = "0.9"
ecdsa = { git = "https://github.com/light-scale/halo2wrong", branch = "ls-dev-0902" }
ecc =       { git = "https://github.com/light-scale/halo2wrong", branch = "ls-dev-0902" }
maingate =  { git = "https://github.com/light-scale/halo2wrong", branch = "ls-dev-0902" }
integer =   { git = "https://github.com/light-scale/halo2wrong", branch = "ls-dev-0902" }
libsecp256k1 = "0.7"
num-bigint = { version = "0.4" }
subtle = "2.4"

[dev-dependencies]
bus-mapping = { path = "../bus-mapping", features = ["test"] }
criterion = "0.3"
ctor = "0.1.22"
hex = "0.4.3"
itertools = "0.10.1"
pretty_assertions = "1.0.0"
ethers-signers = "0.17.0"
rand_chacha = "0.3"

[features]
default = []
kanvas = ["bus-mapping/kanvas", "eth-types/kanvas"]
test = []
