[package]
name = "eth-types"
version = "0.1.0"
edition = "2021"
authors = ["The appliedzkp team"]
license = "MIT OR Apache-2.0"

[dependencies]
ethers-core = "0.6"
ethers-providers = "0.6"
ethers-signers = "0.6"
hex = "0.4"
lazy_static = "1.4"
halo2_proofs = { version = "0.1.0-beta.1" }
regex = "1.5.4"
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
uint = "0.9.1"
itertools = "0.10"

